from db.db_properties import DATABASE_TABLE_BID_STATUS, DATABASE_FIELD_ID, DATABASE_FIELD_MESSAGE_ACTUAL_ROW_ID, \
    DATABASE_FIELD_USER_ID, DATABASE_FIELD_BID_STATUS, DATABASE_TABLE_MESSAGE_USER
from utils.enums.status import BidStatus

DATABASE_REQUEST_CREATE_BID_STATUS = f'''CREATE TABLE IF NOT EXISTS {DATABASE_TABLE_BID_STATUS} (
    {DATABASE_FIELD_ID} INTEGER PRIMARY KEY AUTOINCREMENT,
    {DATABASE_FIELD_USER_ID} INTEGER,
    {DATABASE_FIELD_MESSAGE_ACTUAL_ROW_ID} INTEGER,
    {DATABASE_FIELD_BID_STATUS} INTEGER DEFAULT {BidStatus.CREATED.code})'''

DATABASE_REQUEST_SAVE_BID_STATUS = f'''
    INSERT INTO {DATABASE_TABLE_BID_STATUS} (
        {DATABASE_FIELD_USER_ID},
        {DATABASE_FIELD_MESSAGE_ACTUAL_ROW_ID},
        {DATABASE_FIELD_BID_STATUS}
    ) VALUES (?, ?, ?)'''

DATABASE_REQUEST_UPDATE_BID_STATUS = f'''
    UPDATE {DATABASE_TABLE_BID_STATUS}
    SET {DATABASE_FIELD_BID_STATUS} = ?
    WHERE {DATABASE_FIELD_MESSAGE_ACTUAL_ROW_ID} = ?'''

DATABASE_REQUEST_GET_ALL_MESSAGES_BY_BID_STATUS = f'''
    SELECT msgs.*
    FROM {DATABASE_TABLE_BID_STATUS} bstatus
    JOIN {DATABASE_TABLE_MESSAGE_USER} msgs
    ON msgs.{DATABASE_FIELD_ID} = bstatus.{DATABASE_FIELD_MESSAGE_ACTUAL_ROW_ID}
    WHERE bstatus.{DATABASE_FIELD_BID_STATUS} = ?'''

DATABASE_REQUEST_GET_USER_MESSAGES_BY_BID_STATUS = f'''
    SELECT msgs.*
    FROM {DATABASE_TABLE_BID_STATUS} bstatus
    JOIN {DATABASE_TABLE_MESSAGE_USER} msgs
    ON msgs.{DATABASE_FIELD_ID} = bstatus.{DATABASE_FIELD_MESSAGE_ACTUAL_ROW_ID}
    WHERE msgs.{DATABASE_FIELD_USER_ID} = ? AND bstatus.{DATABASE_FIELD_BID_STATUS} = ?'''

DATABASE_REQUEST_DELETE_BID_STATUS = f'''DELETE FROM {DATABASE_TABLE_BID_STATUS} WHERE {DATABASE_FIELD_MESSAGE_ACTUAL_ROW_ID} = ?'''
