from db.db_properties import DATABASE_TABLE_MESSAGE_BOT, DATABASE_FIELD_ID, DATABASE_FIELD_MESSAGE_TAG, \
    DATABASE_FIELD_CHAT_ID, DATABASE_FIELD_TOPIC_ID, DATABASE_FIELD_USER_ID, DATABASE_FIELD_MESSAGE_BOT_ID

DATABASE_REQUEST_CREATE_MESSAGE_BOT = f'''CREATE TABLE IF NOT EXISTS {DATABASE_TABLE_MESSAGE_BOT} (
    {DATABASE_FIELD_ID} INTEGER PRIMARY KEY AUTOINCREMENT,
    {DATABASE_FIELD_CHAT_ID} INTEGER,
    {DATABASE_FIELD_TOPIC_ID} INTEGER,
    {DATABASE_FIELD_USER_ID} INTEGER,
    {DATABASE_FIELD_MESSAGE_TAG} TEXT,
    {DATABASE_FIELD_MESSAGE_BOT_ID} INTEGER,
    UNIQUE({DATABASE_FIELD_CHAT_ID}, {DATABASE_FIELD_TOPIC_ID}, {DATABASE_FIELD_USER_ID}, {DATABASE_FIELD_MESSAGE_TAG})
)'''

DATABASE_REQUEST_SAVE_MESSAGE_BOT = f'''
    INSERT INTO {DATABASE_TABLE_MESSAGE_BOT} (
        {DATABASE_FIELD_CHAT_ID},
        {DATABASE_FIELD_TOPIC_ID},
        {DATABASE_FIELD_USER_ID},
        {DATABASE_FIELD_MESSAGE_TAG},
        {DATABASE_FIELD_MESSAGE_BOT_ID}
    ) VALUES (?, ?, ?, ?, ?) '''

DATABASE_REQUEST_GET_BOT_MESSAGE = f'''
    SELECT * FROM {DATABASE_TABLE_MESSAGE_BOT} 
    WHERE 
        {DATABASE_FIELD_CHAT_ID} = ? AND 
       ({DATABASE_FIELD_TOPIC_ID} IS ? OR {DATABASE_FIELD_TOPIC_ID} IS NULL)
'''

DATABASE_REQUEST_DELETE_BOT_MESSAGE = f'''
    DELETE FROM {DATABASE_TABLE_MESSAGE_BOT} 
    WHERE 
        {DATABASE_FIELD_CHAT_ID} = ? AND 
       ({DATABASE_FIELD_TOPIC_ID} IS ? OR {DATABASE_FIELD_TOPIC_ID} IS NULL)
'''
