from db.db_properties import DATABASE_TABLE_MESSAGE_USER, DATABASE_FIELD_ID, DATABASE_FIELD_CHAT_ID, \
    DATABASE_FIELD_TOPIC_ID, DATABASE_FIELD_USER_ID, DATABASE_FIELD_MESSAGE_USER_ID, DATABASE_FIELD_MESSAGE_TEXT

DATABASE_REQUEST_CREATE_TABLE_MESSAGE_USER = f'''CREATE TABLE IF NOT EXISTS {DATABASE_TABLE_MESSAGE_USER} (
    {DATABASE_FIELD_ID} INTEGER PRIMARY KEY AUTOINCREMENT,
    {DATABASE_FIELD_CHAT_ID} INTEGER,
    {DATABASE_FIELD_TOPIC_ID} INTEGER,
    {DATABASE_FIELD_USER_ID} INTEGER,
    {DATABASE_FIELD_MESSAGE_USER_ID} INTEGER,
    {DATABASE_FIELD_MESSAGE_TEXT} TEXT)'''

DATABASE_REQUEST_CREATE_USER_ID_INDEX = f'''CREATE INDEX IF NOT EXISTS idx_{DATABASE_FIELD_USER_ID} ON {DATABASE_TABLE_MESSAGE_USER}({DATABASE_FIELD_USER_ID})'''

DATABASE_REQUEST_SAVE_MESSAGE_USER = f'''INSERT INTO {DATABASE_TABLE_MESSAGE_USER} (
    {DATABASE_FIELD_CHAT_ID},
    {DATABASE_FIELD_TOPIC_ID},
    {DATABASE_FIELD_USER_ID}, 
    {DATABASE_FIELD_MESSAGE_USER_ID},
    {DATABASE_FIELD_MESSAGE_TEXT}
    ) VALUES (?, ?, ?, ?, ?) ON CONFLICT({DATABASE_FIELD_ID}) DO UPDATE SET {DATABASE_FIELD_MESSAGE_TEXT}=excluded.{DATABASE_FIELD_MESSAGE_TEXT}'''

DATABASE_REQUEST_GET_USER_MESSAGES = f'''SELECT * FROM {DATABASE_TABLE_MESSAGE_USER} WHERE {DATABASE_FIELD_USER_ID} = ?'''

DATABASE_REQUEST_GET_USER_MESSAGE_ROW_ID = f'''SELECT {DATABASE_FIELD_ID} FROM {DATABASE_TABLE_MESSAGE_USER} 
    WHERE {DATABASE_FIELD_CHAT_ID} = ? 
    AND {DATABASE_FIELD_TOPIC_ID} = ? 
    AND {DATABASE_FIELD_MESSAGE_USER_ID} = ? 
    AND {DATABASE_FIELD_USER_ID} = ?'''

DATABASE_REQUEST_DELETE_USER_MESSAGE = f'''DELETE FROM {DATABASE_TABLE_MESSAGE_USER} WHERE {DATABASE_FIELD_ID} = ?'''

DATABASE_REQUEST_GET_USER_IDS_COUNT = f'''SELECT COUNT(DISTINCT {DATABASE_FIELD_USER_ID}) FROM {DATABASE_TABLE_MESSAGE_USER}'''
DATABASE_REQUEST_GET_USER_IDS = f'''SELECT {DATABASE_FIELD_USER_ID} FROM {DATABASE_TABLE_MESSAGE_USER} LIMIT ? OFFSET ?'''

def DATABASE_REQUEST_GET_MESSAGES_BY_ENCRYPTED_USER_IDS(placeholders: str):
    return f'''SELECT * FROM {DATABASE_TABLE_MESSAGE_USER} WHERE {DATABASE_FIELD_USER_ID} in ({placeholders})'''
