from typing import TypeVar

T = TypeVar("T")

MESSAGE_POST_SYMBOLS_LIMIT = 4096
MESSAGE_SHORT_TEXT_ROW_LENGTH = 60

TELEGRAM_LINK_START_POINT = "https://t.me/"
CIPHER_KEY_FILE_NAME = ".encryption_key"

PARSE_MODE_MARKDOWN = "MarkdownV2"
PARSE_MODE_HTML = "HTML"

CHAT_BOT_COMMAND_START = "start"
CHAT_BOT_COMMAND_HELP = "help"

TAG_BOT_SHOW_ALL_USER_MESSAGES = "user"

CHECKLIST_TAG_MESSAGES = "messages_"
CHECKLIST_TAG_PLAYERS = "players_"
CHECKLIST_TAG_CHECK_UPDATE = "checklist_check_update_"

BUTTON_CALLBACK_COMMON_TAG = "__tag__"

BUTTON_CALLBACK_TAG_PLAYER_MESSAGES = f"{BUTTON_CALLBACK_COMMON_TAG}player_messages_"
BUTTON_CALLBACK_TAG_PLAYER_IGNORE = f"{BUTTON_CALLBACK_COMMON_TAG}player_ignore_"
BUTTON_CALLBACK_TAG_PLAYER_FORGET = f"{BUTTON_CALLBACK_COMMON_TAG}player_forget_"
BUTTON_CALLBACK_TAG_PLAYER_PROCESSING = f"{BUTTON_CALLBACK_COMMON_TAG}player_processing_"

BUTTON_CALLBACK_TAG_MODERATE_IGNORE = f"{BUTTON_CALLBACK_COMMON_TAG}moderate_ignore_"
BUTTON_CALLBACK_TAG_MODERATE_FORGET = f"{BUTTON_CALLBACK_COMMON_TAG}moderate_forget_moderate_"
BUTTON_CALLBACK_TAG_MODERATE_PROCESSED_MARK = f"{BUTTON_CALLBACK_COMMON_TAG}moderate_processed_mark_"
BUTTON_CALLBACK_TAG_MODERATE_PROCESSED_FIX = f"{BUTTON_CALLBACK_COMMON_TAG}moderate_processed_fix_"
BUTTON_CALLBACK_TAG_MODERATE_PLAYERS_SELECT = f"{BUTTON_CALLBACK_COMMON_TAG}players_select_"

BUTTON_CALLBACK_CALL_PLAYERS_TO_BID_START = f"{BUTTON_CALLBACK_COMMON_TAG}call_to_bid_start_"
BUTTON_CALLBACK_CALL_PLAYERS_TO_BID_STOP = f"{BUTTON_CALLBACK_COMMON_TAG}call_to_bid_stop_"
